data_name: "BZ5"
r: 700
replicate: "_testgeneonly"
tissue_region: "mPFC region of mice"
celltype_name: "cell_type"
pos_name: ["x", "y"]
name_truth: "niche_truth"
model_type: "zeroshot_end2end"
openai_url: "/v1/chat/completions"
use_full_name: true
with_self_type: true
with_region_name: true
Graph_type: "GeneOnly"  # "count" or "countPlusGenes" or "GeneOnly"
with_negatives: false
minimal_f: 0  # this should adjust according to the neighbor_count
top_n: 10  # this should adjust according to the neighbor_count and number of cell types
with_numbers: true
with_domain_name: true
gpt_model: "gpt-4o-mini"
oneshot_prompt: ""
system_prompt: ""
output_type: "niche"
confident_output: false

