data_name: "Exp1"
r: 500  # IMPORTANT !!!!
replicate: "_rep1R500"  # IMPORTANT !!!!
name_truth: None
tissue_region: "Human lung adenocarcinoma"
model_type: "zeroshot_end2end"  # IMPORTANT !!!!
openai_url: "/v1/chat/completions"
use_full_name: false  # because the full cell type names are already in the data
with_self_type: false
with_region_name: true
Graph_type: "countPlusGenes"  # IMPORTANT !!!!
with_negatives: false
with_CoT: false
minimal_f: 0.1  # this should adjust according to the neighbor_count
top_n: 10  # this should adjust according to the neighbor_count and number of cell types
with_numbers: false
with_domain_name: true
gpt_model: "gpt-4o-mini"  # IMPORTANT !!!!
output_type: "niche"
minimal_gene_threshold: 0

