data_name: "MERFISH_29"
r: 100  # IMPORTANT !!!!
replicate: "_rep3R100"  # IMPORTANT !!!!
name_truth: "ground_truth"
tissue_region: "mouse hypothalamic preoptic region"
model_type: "finetunePro_MERFISH25"  # IMPORTANT !!!! choose correct base data name
openai_url: "/v1/chat/completions"
use_full_name: false  # because the full cell type names are already in the data
with_self_type: false
with_region_name: true
Graph_type: "countPlusGenes"
with_negatives: false  # IMPORTANT !!!!
with_CoT: false
minimal_f: 0.1  # this should adjust according to the neighbor_count
top_n: 10  # this should adjust according to the neighbor_count and number of cell types
with_numbers: false
with_domain_name: true
gpt_model: "ft:gpt-4o-mini-2024-07-18:personal:finetunepro-merfish250-3-100-newgenes:AWXjqn26"  # IMPORTANT !!!!
oneshot_prompt: ""
system_prompt: ""
output_type: "niche"
minimal_gene_threshold: 0
prototype_p: 0.3  # IMPORTANT !!!!
