data_name: "BZ5"
r: 700
replicate: "_rep1"
name_truth: "niche_truth"
tissue_region: "mPFC region of mice"
model_type: "zeroshot_end2end"
openai_url: "/v1/chat/completions"
use_full_name: true
with_self_type: false
with_region_name: true
Graph_type: "count"
with_negatives: true
with_CoT: false
minimal_f: 0  # this should adjust according to the neighbor_count
top_n: 99  # this should adjust according to the neighbor_count and number of cell types
with_numbers: false
with_domain_name: true
gpt_model: "gpt-4o-mini"
oneshot_prompt: ""
system_prompt: ""
output_type: "niche"
